package moe.afox.dpsandbox.core

import com.google.gson.JsonArray
import com.google.gson.JsonElement
import com.google.gson.JsonObject
import kotlin.math.floor
import kotlin.random.Random

/**
 * Context used when generating a loot table.
 *
 * The sandbox requires callers to provide any world/entity/tool context that
 * loot conditions or functions need. Missing required context fails explicitly
 * instead of silently producing vanilla-like fallback behavior.
 */
data class LootContext(
    /** Loot context type, for example `minecraft:command` or `minecraft:advancement_reward`. */
    val type: ResourceLocation = ResourceLocation("minecraft", "empty"),
    /** Predicate context shared by loot conditions and item filters. */
    val predicateContext: PredicateContext,
    /** Deterministic seed used for this generation call. */
    val seed: Long = 0,
    /** Tool stack used by loot functions such as copy/set behavior. */
    val tool: ItemStack? = predicateContext.tool,
    /** Luck value exposed for loot calculations that support it. */
    val luck: Double = 0.0,
)

/**
 * Items generated by one loot table execution.
 */
data class LootResult(val items: List<ItemStack>)

/**
 * Clean-room loot table executor for loaded datapack loot resources.
 */
class LootEngine(
    private val datapack: Datapack,
    private val registry: RegistryView = RegistryView.vanilla262,
    private val profile: VersionProfile = VersionProfiles.default,
) {
    private val predicates = PredicateEngine(datapack, profile)

    /**
     * Generates items from loot table [id] using [context].
     *
     * The output is deterministic for a fixed table, context, and seed.
     *
     * @throws SandboxException when the table is missing, has the wrong context
     * type, references missing context, or uses an unsupported loot feature.
     */
    fun generate(id: ResourceLocation, context: LootContext): LootResult {
        val table = datapack.lootTable(id)
        return generateTable(table, context, mutableSetOf())
    }

    private fun generateTable(table: LootTable, context: LootContext, stack: MutableSet<ResourceLocation>): LootResult {
        if (!stack.add(table.id)) {
            throw SandboxException(DiagnosticCode.COMMAND_ERROR, "Recursive loot table reference: ${table.id}")
        }
        try {
            table.root.string("type")?.let { expected ->
                val expectedId = ResourceLocation.parse(expected)
                if (expectedId != context.type) {
                    throw SandboxException(
                        DiagnosticCode.MISSING_CONTEXT,
                        "Loot table '${table.id}' expects context '$expectedId' but got '${context.type}'",
                        location = SourceLocation(file = table.file),
                    )
                }
            }

            val random = Random(context.seed xor table.id.toString().hashCode().toLong())
            val tableFunctions = table.root.arrayObjects("functions").map { LootFunction(canonical(it.requiredString("function")), it) }
            val results = mutableListOf<ItemStack>()
            table.root.getAsJsonArray("pools")?.forEach { poolElement ->
                if (!poolElement.isJsonObject) throw tableError(table, "Loot pool must be an object")
                val pool = poolElement.asJsonObject
                if (!testConditions(pool.get("conditions"), context)) return@forEach
                val rolls = rollCount(pool.get("rolls"), random) + (pool.get("bonus_rolls")?.let { rollCount(it, random) } ?: 0)
                repeat(rolls.coerceAtLeast(0)) {
                    val entry = chooseEntry(pool.arrayObjects("entries"), context, random, stack)
                    if (entry != null) {
                        val poolFunctions = pool.arrayObjects("functions").map { LootFunction(canonical(it.requiredString("function")), it) }
                        results += applyFunctions(entry, poolFunctions, context, random)
                    }
                }
            }
            return LootResult(applyFunctions(results, tableFunctions, context, random))
        } finally {
            stack.remove(table.id)
        }
    }

    private fun chooseEntry(entries: List<JsonObject>, context: LootContext, random: Random, stack: MutableSet<ResourceLocation>): List<ItemStack>? {
        val candidates = entries.filter { testConditions(it.get("conditions"), context) }
        if (candidates.isEmpty()) return null
        val weighted = candidates.map { it to (it.get("weight")?.asInt ?: 1).coerceAtLeast(0) }
        val total = weighted.sumOf { it.second }
        val chosen = if (total <= 0) candidates.first() else {
            var cursor = random.nextInt(total)
            weighted.first { (_, weight) ->
                cursor -= weight
                cursor < 0
            }.first
        }
        return expandEntry(chosen, context, random, stack)
    }

    private fun expandEntry(entry: JsonObject, context: LootContext, random: Random, stack: MutableSet<ResourceLocation>): List<ItemStack> {
        val type = canonical(entry.requiredString("type"))
        val functions = entry.arrayObjects("functions").map { LootFunction(canonical(it.requiredString("function")), it) }
        val base = when (type) {
            "empty" -> emptyList()
            "item" -> listOf(ItemStack(ResourceLocation.parse(entry.requiredString("name"))))
            "loot_table" -> generateTable(datapack.lootTable(ResourceLocation.parse(entry.requiredString("value"))), context, stack).items
            "group" -> entry.arrayObjects("children").flatMap { expandEntry(it, context, random, stack) }
            "alternatives" -> {
                val child = entry.arrayObjects("children").firstOrNull { testConditions(it.get("conditions"), context) }
                child?.let { expandEntry(it, context, random, stack) } ?: emptyList()
            }
            "sequence" -> {
                val output = mutableListOf<ItemStack>()
                for (child in entry.arrayObjects("children")) {
                    if (!testConditions(child.get("conditions"), context)) break
                    output += expandEntry(child, context, random, stack)
                }
                output
            }
            "dynamic" -> emptyList()
            "tag" -> expandItemTag(ResourceLocation.parse(entry.requiredString("name")), mutableSetOf()).map { ItemStack(it) }
            else -> throw SandboxException(DiagnosticCode.UNSUPPORTED_FEATURE, "Loot entry type '${entry.requiredString("type")}' is not implemented")
        }
        return applyFunctions(base, functions, context, random)
    }

    private fun expandItemTag(id: ResourceLocation, stack: MutableSet<ResourceLocation>): List<ResourceLocation> {
        if (!stack.add(id)) {
            throw SandboxException(DiagnosticCode.COMMAND_ERROR, "Recursive item tag reference: $id")
        }
        try {
            val tag = itemTag(id)
            return tag.values.flatMap { value ->
                if (value.id.startsWith("#")) {
                    val nested = ResourceLocation.parse(value.id.removePrefix("#"))
                    val nestedTag = findItemTag(nested)
                    if (nestedTag == null) {
                        if (value.required) {
                            throw SandboxException(DiagnosticCode.RESOURCE_NOT_FOUND, "Item tag '$nested' referenced by '$id' was not found")
                        }
                        emptyList()
                    } else {
                        expandItemTag(nestedTag.key.id, stack)
                    }
                } else {
                    listOf(ResourceLocation.parse(value.id))
                }
            }
        } finally {
            stack.remove(id)
        }
    }

    private fun itemTag(id: ResourceLocation): TagDefinition =
        findItemTag(id)
            ?: throw SandboxException(DiagnosticCode.RESOURCE_NOT_FOUND, "Item tag '$id' was not found")

    private fun findItemTag(id: ResourceLocation): TagDefinition? =
        datapack.tags[TagKey("item", id)] ?: datapack.tags[TagKey("items", id)]

    private fun testConditions(conditions: JsonElement?, context: LootContext): Boolean =
        predicates.testConditions(conditions, context.predicateContext)

    private fun applyFunctions(items: List<ItemStack>, functions: List<LootFunction>, context: LootContext, random: Random): List<ItemStack> =
        items.flatMap { item -> applyFunctions(item, functions, context, random) }

    private fun applyFunctions(item: ItemStack, functions: List<LootFunction>, context: LootContext, random: Random): List<ItemStack> {
        var stack = item.copy(components = item.components.deepCopy(), nbt = item.nbt.deepCopy())
        functions.forEach { function ->
            if (!testConditions(function.root.get("conditions"), context)) return@forEach
            when (function.type) {
                "set_count" -> stack.count = rollCount(function.root.get("count"), random).coerceAtLeast(0)
                "limit_count" -> stack.count = limit(stack.count, function.root.get("limit"))
                "set_components" -> function.root.getAsJsonObject("components")?.entrySet()?.forEach { (key, value) ->
                    stack.components.add(key, value.deepCopy())
                }
                "set_custom_data", "set_nbt" -> function.root.string("tag")?.let {
                    val parsed = JsonValues.parse(it)
                    if (parsed.isJsonObject) JsonPaths.merge(stack.nbt, null, parsed)
                }
                "set_item" -> stack = stack.copy(id = ResourceLocation.parse(function.root.requiredString("item")))
                "discard" -> return emptyList()
                "set_damage" -> stack.components.addProperty("minecraft:damage", rollDouble(function.root.get("damage"), random))
                "set_name" -> stack.components.add("minecraft:custom_name", lootFunctionText(function.root, "name", function.type))
                "set_lore" -> stack.components.add("minecraft:lore", lootFunctionLore(function.root))
                "copy_nbt", "copy_components" -> copyFromContext(stack, function, context)
                "explosion_decay" -> stack.count = if (context.predicateContext.random.nextBoolean()) stack.count else 0
                "apply_bonus" -> stack.count = applyBonus(stack.count, function.root, context, random).coerceAtLeast(0)
                "enchant_randomly" -> addEnchantment(stack, chooseEnchantment(function.root, random), 1)
                "enchant_with_levels" -> addEnchantment(
                    stack,
                    chooseEnchantment(function.root, random),
                    rollCount(function.root.get("levels"), random).coerceAtLeast(1),
                )
                "filtered" -> {
                    val itemFilter = function.root.getAsJsonObject("item_filter") ?: function.root.getAsJsonObject("filter")
                    if (itemFilter != null && !predicates.testItemPredicate(stack, itemFilter)) return emptyList()
                    val inner = function.root.getAsJsonObject("function")
                        ?: throw SandboxException(DiagnosticCode.INPUT_FORMAT, "filtered loot function requires nested function")
                    stack = applyFunctions(stack, listOf(LootFunction(canonical(inner.requiredString("function")), inner)), context, random).firstOrNull()
                        ?: return emptyList()
                }
                "sequence" -> {
                    val nested = function.root.arrayObjects("functions").map { LootFunction(canonical(it.requiredString("function")), it) }
                    stack = applyFunctions(stack, nested, context, random).firstOrNull() ?: return emptyList()
                }
                else -> throw SandboxException(DiagnosticCode.UNSUPPORTED_FEATURE, "Loot function '${function.type}' is not implemented")
            }
        }
        return if (stack.count <= 0) emptyList() else listOf(stack)
    }

    private fun applyBonus(count: Int, root: JsonObject, context: LootContext, random: Random): Int {
        val enchantment = ResourceLocation.parse(root.requiredString("enchantment"))
        val level = toolEnchantmentLevel(context.tool, enchantment)
        if (level <= 0) return count
        val formula = root.string("formula")?.let(::canonical) ?: "uniform_bonus_count"
        val parameters = root.getAsJsonObject("parameters") ?: JsonObject()
        return when (formula) {
            "binomial_with_bonus_count" -> {
                var result = count
                val extra = parameters.get("extra")?.asInt ?: 0
                val probability = parameters.get("probability")?.asDouble ?: 0.0
                repeat((level + extra).coerceAtLeast(0)) {
                    if (random.nextDouble() < probability) result++
                }
                result
            }
            "uniform_bonus_count" -> {
                val multiplier = parameters.get("bonusMultiplier")?.asInt
                    ?: parameters.get("bonus_multiplier")?.asInt
                    ?: 1
                val bound = (level * multiplier).coerceAtLeast(0)
                count + if (bound == 0) 0 else random.nextInt(bound + 1)
            }
            "ore_drops" -> count * random.nextInt(level + 2).coerceAtLeast(1)
            else -> throw SandboxException(DiagnosticCode.UNSUPPORTED_FEATURE, "Loot apply_bonus formula '$formula' is not implemented")
        }
    }

    private fun toolEnchantmentLevel(tool: ItemStack?, enchantment: ResourceLocation): Int {
        val enchantments = tool?.components?.getAsJsonObject("minecraft:enchantments") ?: return 0
        return enchantments.get(enchantment.toString())?.takeIf { it.isJsonPrimitive }?.asInt
            ?: enchantments.get(enchantment.path)?.takeIf { it.isJsonPrimitive }?.asInt
            ?: 0
    }

    private fun chooseEnchantment(root: JsonObject, random: Random): ResourceLocation {
        val options = enchantmentOptions(root.get("options") ?: root.get("enchantments") ?: root.get("enchantment"))
        return if (options.size == 1) options.single() else options[random.nextInt(options.size)]
    }

    private fun enchantmentOptions(element: JsonElement?): List<ResourceLocation> =
        when {
            element == null || element.isJsonNull -> registry.enchantments.sorted()
            element.isJsonPrimitive && element.asJsonPrimitive.isString -> listOf(ResourceLocation.parse(element.asString))
            element.isJsonArray -> element.asJsonArray.mapIndexed { index, entry ->
                if (!entry.isJsonPrimitive || !entry.asJsonPrimitive.isString) {
                    throw SandboxException(DiagnosticCode.INPUT_FORMAT, "Loot enchantment option at index $index must be a string")
                }
                ResourceLocation.parse(entry.asString)
            }.ifEmpty {
                throw SandboxException(DiagnosticCode.INPUT_FORMAT, "Loot enchantment options must not be empty")
            }
            else -> throw SandboxException(DiagnosticCode.INPUT_FORMAT, "Loot enchantment options must be a string or array of strings")
        }

    private fun addEnchantment(stack: ItemStack, enchantment: ResourceLocation, level: Int) {
        val existing = stack.components.get("minecraft:enchantments")
        val enchantments = if (existing != null && existing.isJsonObject) {
            existing.asJsonObject
        } else {
            JsonObject().also { stack.components.add("minecraft:enchantments", it) }
        }
        enchantments.addProperty(enchantment.toString(), level.coerceAtLeast(1))
    }

    private fun copyFromContext(stack: ItemStack, function: LootFunction, context: LootContext) {
        val source = function.root.string("source") ?: "this"
        val entity = when (source) {
            "this" -> context.predicateContext.thisEntity
            "attacker" -> context.predicateContext.attacker
            "killer" -> context.predicateContext.killer
            "tool" -> null
            else -> null
        }
        if (function.type == "copy_nbt") {
            val sourceNbt = when (source) {
                "tool" -> context.tool?.nbt
                else -> entity?.nbt
            } ?: throw SandboxException(DiagnosticCode.MISSING_CONTEXT, "copy_nbt requires source context '$source'")
            function.root.getAsJsonArray("ops")?.forEach { op ->
                val objectOp = op.asJsonObject
                val value = JsonPaths.get(sourceNbt, objectOp.requiredString("source")) ?: return@forEach
                JsonPaths.set(stack.nbt, objectOp.requiredString("target"), value)
            }
        }
        if (function.type == "copy_components") {
            val sourceComponents = componentSource(source, context)
            val include = componentIdList(function.root.get("include"), "include")
            val exclude = componentIdList(function.root.get("exclude"), "exclude").orEmpty().toSet()
            val names = (include ?: sourceComponents.entrySet().map { it.key }.sorted())
                .distinct()
                .filterNot { it in exclude }
            names.forEach { name ->
                sourceComponents.get(name)?.let { stack.components.add(name, it.deepCopy()) }
            }
        }
    }

    private fun componentSource(source: String, context: LootContext): JsonObject {
        val playerItem = when (source) {
            "this" -> (context.predicateContext.thisEntity as? SandboxPlayer)?.selectedItem ?: context.predicateContext.player?.selectedItem
            "attacker" -> (context.predicateContext.attacker as? SandboxPlayer)?.selectedItem
            "direct_attacker" -> (context.predicateContext.directEntity as? SandboxPlayer)?.selectedItem
            "killer" -> (context.predicateContext.killer as? SandboxPlayer)?.selectedItem
            "tool" -> context.tool
            else -> null
        }
        return playerItem?.components
            ?: throw SandboxException(DiagnosticCode.MISSING_CONTEXT, "copy_components requires item component source '$source'")
    }

    private fun componentIdList(element: JsonElement?, key: String): List<String>? {
        if (element == null || element.isJsonNull) return null
        return when {
            element.isJsonPrimitive && element.asJsonPrimitive.isString ->
                listOf(ResourceLocation.parse(element.asString).toString())
            element.isJsonArray -> element.asJsonArray.mapIndexed { index, value ->
                if (!value.isJsonPrimitive || !value.asJsonPrimitive.isString) {
                    throw SandboxException(DiagnosticCode.INPUT_FORMAT, "copy_components '$key' entries must be strings at index $index")
                }
                ResourceLocation.parse(value.asString).toString()
            }
            else -> throw SandboxException(DiagnosticCode.INPUT_FORMAT, "copy_components '$key' must be a string or array of strings")
        }
    }

    private fun lootFunctionText(root: JsonObject, key: String, type: String): JsonElement =
        root.get(key)?.deepCopy()
            ?: throw SandboxException(DiagnosticCode.INPUT_FORMAT, "Loot function '$type' requires '$key'")

    private fun lootFunctionLore(root: JsonObject): JsonArray {
        val lore = root.get("lore") ?: throw SandboxException(DiagnosticCode.INPUT_FORMAT, "Loot function 'set_lore' requires 'lore'")
        if (!lore.isJsonArray) {
            throw SandboxException(DiagnosticCode.INPUT_FORMAT, "Loot function 'set_lore' lore must be an array")
        }
        return lore.deepCopy().asJsonArray
    }

    private fun rollCount(element: JsonElement?, random: Random): Int =
        floor(rollDouble(element, random)).toInt()

    private fun rollDouble(element: JsonElement?, random: Random): Double =
        when {
            element == null || element.isJsonNull -> 1.0
            element.isJsonPrimitive -> element.asDouble
            element.isJsonObject -> {
                val objectElement = element.asJsonObject
                val min = objectElement.get("min")?.asDouble ?: objectElement.get("base")?.asDouble ?: 0.0
                val max = objectElement.get("max")?.asDouble ?: min
                if (max <= min) min else min + random.nextDouble() * (max - min)
            }
            else -> 1.0
        }

    private fun limit(value: Int, limit: JsonElement?): Int {
        if (limit == null || !limit.isJsonObject) return value
        val root = limit.asJsonObject
        val min = root.get("min")?.asInt ?: Int.MIN_VALUE
        val max = root.get("max")?.asInt ?: Int.MAX_VALUE
        return value.coerceIn(min, max)
    }

    private fun canonical(raw: String): String = ResourceLocation.parse(raw).path

    private fun tableError(table: LootTable, message: String): SandboxException =
        SandboxException(DiagnosticCode.INPUT_FORMAT, message, SourceLocation(file = table.file))

    private fun JsonObject.arrayObjects(name: String): List<JsonObject> =
        getAsJsonArray(name)?.map {
            if (!it.isJsonObject) throw SandboxException(DiagnosticCode.INPUT_FORMAT, "Array '$name' must contain objects")
            it.asJsonObject
        } ?: emptyList()

    private fun JsonObject.string(name: String): String? =
        get(name)?.takeIf { it.isJsonPrimitive }?.asString

    private fun JsonObject.requiredString(name: String): String =
        string(name) ?: throw SandboxException(DiagnosticCode.INPUT_FORMAT, "Missing required string '$name'")
}
